### ISSUE TITLE
No provider for AlainConfigService

### ISSUE THREAD

**Issue by zmzimpl** [ng-alain/ng-alain#1624]
- ng-alain version: 9.1.0
- Angular version: 9.1.4

## 重现步骤，Steps to reproduce
升级到9之后，启动的时候浏览器控制台报错了
![image](https://user-images.githubusercontent.com/27490895/80908976-e52f2f00-8d56-11ea-8206-10d3a3914bf9.png)

**Comment by cipchk** [comment]
试着在 `app.module.ts` 增加：

```ts
providers: [ AlainConfigService ],
```

好像有部分会引起这类，但目前我没也没遇到过，感觉像是 lvy 产生的。

**Comment by zmzimpl** [comment]
> 试着在 `app.module.ts` 增加：
> 
> ```ts
> providers: [ AlainConfigService ],
> ```
> 
> 好像有部分会引起这类，但目前我没也没遇到过，感觉像是 lvy 产生的。

再app.module.ts内引入后解决了，多谢~

**Comment by LooJee** [comment]
![image](https://user-images.githubusercontent.com/13059033/81138532-f36a8e80-8f94-11ea-97c2-991201348785.png)
![image](https://user-images.githubusercontent.com/13059033/81138573-0d0bd600-8f95-11ea-9e7a-1aa2dafb47f6.png)
我在 app.module.ts 中添加了 AlainConfigService 之后还是会报错。。。

**Comment by yzpGoGo** [comment]
我的是单独使用的@delon/chart，找不到AlainConfigService这个怎办

**Comment by cipchk** [comment]
> 我的是单独使用的@delon/chart，找不到AlainConfigService这个怎办

要么你单独引用它，要么你通过 https://github.com/ng-alain/delon/blob/master/packages/chart/README.md 找到你需要的部分，复制到你的项目中。

**Comment by boloboloda** [comment]
> 试着在 `app.module.ts` 增加：
> 
> ```ts
> providers: [ AlainConfigService ],
> ```
> 
> 好像有部分会引起这类，但目前我没也没遇到过，感觉像是 lvy 产生的。

我引入了，但是还是会报这个错。
![截屏2020-05-11下午7 45 33](https://user-images.githubusercontent.com/29855529/81558443-40e56200-93c0-11ea-8afc-d8742e912c9e.png)

**Comment by caojianbiao** [comment]
单元测试的时候这个错误几乎是无法避免的，不论驾到那里都会出现，下面是我的测试结果error properties: Object({ ngTempTokenPath: null, ngTokenPath: [ 'ClockService', '_HttpClient', 'AlainConfigService$1', 'AlainConfigService$1' ] })
    at <Jasmine>
    at NullInjector.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:937:1)
    at R3Injector.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:11565:1)
    at R3Injector.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:11565:1)
    at injectInjectorOnly (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:822:1)
    at Module.ɵɵinject (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:827:1)
    at Object._HttpClient_Factory [as factory] (http://localhost:9876/_karma_webpack_/node_modules/@delon/theme/__ivy_ngcc__/fesm5/theme.js:3568:135)
    at R3Injector.hydrate (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:11737:1)
    at R3Injector.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:11554:1)
    at injectInjectorOnly (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:822:1)
    at ɵɵinject (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:827:1)



在app.module亦或是在子module内加入AlainConfigService都会出现

**Comment by cipchk** [comment]
@caojianbiao 能否提供一下测试代码 ？
