### ISSUE TITLE
Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by xingjl6280** [ng-alain/ng-alain#1635]
按照官方教程，创建新项目后，启动报错，

ng-alain版本：9.2.1
node版本：12.16.3
angluar cli版本：9.1.4

**ERROR in TypeError: Cannot read property 'flags' of undefined**
    at resolveAlias (E:\03-Project\26-rtms\06-code\a01.svc.rtms\rtms-web\node_modules\typescript\lib\typescript.js:36513:37)
    at checkAliasSymbol (E:\03-Project\26-rtms\06-code\a01.svc.rtms\rtms-web\node_modules\typescript\lib\typescript.js:64502:26)
    at checkImportBinding (E:\03-Project\26-rtms\06-code\a01.svc.rtms\rtms-web\node_modules\typescript\lib\typescript.js:64534:13)
    at checkImportDeclaration (E:\03-Project\26-rtms\06-code\a01.svc.rtms\rtms-web\node_modules\typescript\lib\typescript.js:64552:29)
    at checkSourceElementWorker (E:\03-Project\26-rtms\06-code\a01.svc.rtms\rtms-web\node_modules\typescript\lib\typescript.js:64961:28)
    at checkSourceElement (E:\03-Project\26-rtms\06-code\a01.svc.rtms\rtms-web\node_modules\typescript\lib\typescript.js:64800:17)
    at Object.forEach (E:\03-Project\26-rtms\06-code\a01.svc.rtms\rtms-web\node_modules\typescript\lib\typescript.js:317:30)
    at checkSourceFileWorker (E:\03-Project\26-rtms\06-code\a01.svc.rtms\rtms-web\node_modules\typescript\lib\typescript.js:65123:20)
    at checkSourceFile (E:\03-Project\26-rtms\06-code\a01.svc.rtms\rtms-web\node_modules\typescript\lib\typescript.js:65091:13)
    at getDiagnosticsWorker (E:\03-Project\26-rtms\06-code\a01.svc.rtms\rtms-web\node_modules\typescript\lib\typescript.js:65179:17)
    at Object.getDiagnostics (E:\03-Project\26-rtms\06-code\a01.svc.rtms\rtms-web\node_modules\typescript\lib\typescript.js:65165:24)
    at E:\03-Project\26-rtms\06-code\a01.svc.rtms\rtms-web\node_modules\typescript\lib\typescript.js:98703:85
    at runWithCancellationToken (E:\03-Project\26-rtms\06-code\a01.svc.rtms\rtms-web\node_modules\typescript\lib\typescript.js:98665:24)
    at getBindAndCheckDiagnosticsForFileNoCache (E:\03-Project\26-rtms\06-code\a01.svc.rtms\rtms-web\node_modules\typescript\lib\typescript.js:98691:20)
    at getAndCacheDiagnostics (E:\03-Project\26-rtms\06-code\a01.svc.rtms\rtms-web\node_modules\typescript\lib\typescript.js:98956:26)
    at getBindAndCheckDiagnosticsForFile (E:\03-Project\26-rtms\06-code\a01.svc.rtms\rtms-web\node_modules\typescript\lib\typescript.js:98688:20)

**Comment by cipchk** [comment]
tracking https://github.com/angular/angular/issues/36993

**Comment by cipchk** [comment]
Angular 9.1.6 solved the problems.
