### ISSUE TITLE
Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by rieonke** [ng-alain/ng-alain#169]
MenuService 里面保存
```
core.js:1427 ERROR TypeError: Cannot read property 'includes' of undefined
    at eval (webpack-internal:///../../../../@delon/theme/services/menu/menu.service.js:112:101)
    at Array.findIndex (native)
    at MenuService.loadShortcut (webpack-internal:///../../../../@delon/theme/services/menu/menu.service.js:112:22)
    at MenuService.resume (webpack-internal:///../../../../@delon/theme/services/menu/menu.service.js:82:14)
    at MenuService.add (webpack-internal:///../../../../@delon/theme/services/menu/menu.service.js:40:14)
    at SafeSubscriber.eval [as _next] (webpack-internal:///../../../../../src/app/core/services/startup.service.ts:53:35)
    at SafeSubscriber.__tryOrUnsub (webpack-internal:///../../../../rxjs/_esm5/Subscriber.js:245:16)
    at SafeSubscriber.next (webpack-internal:///../../../../rxjs/_esm5/Subscriber.js:192:22)
    at Subscriber._next (webpack-internal:///../../../../rxjs/_esm5/Subscriber.js:133:26)
    at Subscriber.next (webpack-internal:///../../../../rxjs/_esm5/Subscriber.js:97:18)
```
`@delon/theme/services/menu/menu.service.js`

```
    function (shortcuts) {
        if (shortcuts.length === 0 || this.data.length === 0)
            return;
        var ls = this.data[0].children || [];
        var pos = ls.findIndex(function (w) { return w.shortcut_root === true; });
        if (pos === -1) {
            pos = ls.findIndex(function (w) { return w.link.includes('dashboard') || w.externalLink.includes('dashboard'); });
                                                                                 ^^^^^^^^^ 这里w.externalLink 是undefined
            pos = (pos !== -1 ? pos : -1) + 1;
            this.data[0].children.splice(pos, 0, {
                text: '快捷菜单',
                translate: 'shortcut',
                icon: 'icon-rocket',
                children: []
            });
        }
        var _data = this.data[0].children[pos];
        _data = Object.assign(_data, {
            shortcut_root: true,
            _type: 3,
            __id: -1,
            _depth: 1
        });
        _data.children = shortcuts.map(function (i) {
            i._depth = 2;
            return i;
        });
    };
```

**Comment by cipchk** [comment]
confirmed, thx.

**Comment by rieonke** [comment]
已经提交了PR cipchk/delon#11
