### ISSUE TITLE
ng build --prod error

### ISSUE THREAD

**Issue by OffieCao** [ng-alain/ng-alain#293]
**ng-alain使用ng build --prod模式编译报错**

## Steps to reproduce

**1. 拿到ng-alain代码后使用cnpm install
2. ng build, success!
3. ng build --prod (npm run build), error!
error1: ngx-ueditor. Do: remove ngx-ueditor and the module.
error2: ng-tree-antd, ng-clipboard-antd. Do: remove.
4. ng build --prod (npm run build), error!**
<pre><code>
Unhandled rejection Error: ENOENT: no such file or directory, open 'D:\Project\ng-alain-update\ng-alain-master\node_modules\._@angular_animations@5.2.4@@angular\package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at LicenseExtractor.readPackageJson (D:\Project\ng-alain-update\ng-alain-master\node_modules\._license-webpack-plugin@1.1.1@license-webpack-plugin\dist\LicenseExtractor.js:124:23)
    at LicenseExtractor.parsePackage (D:\Project\ng-alain-update\ng-alain-master\node_modules\._license-webpack-plugin@1.1.1@license-webpack-plugin\dist\LicenseExtractor.js:21:32)
    at ModuleProcessor.processPackage (D:\Project\ng-alain-update\ng-alain-master\node_modules\._license-webpack-plugin@1.1.1@license-webpack-plugin\dist\ModuleProcessor.js:24:46)
    at ModuleProcessor.processFile (D:\Project\ng-alain-update\ng-alain-master\node_modules\._license-webpack-plugin@1.1.1@license-webpack-plugin\dist\ModuleProcessor.js:21:21)
    at moduleCallback (D:\Project\ng-alain-update\ng-alain-master\node_modules\._license-webpack-plugin@1.1.1@license-webpack-plugin\dist\LicenseWebpackPlugin.js:80:61)
    at SortableSet.forEach (native)
    at Chunk.forEachModule (D:\Project\ng-alain-update\ng-alain-master\node_modules\._webpack@3.10.0@webpack\lib\Chunk.js:159:17)
    at D:\Project\ng-alain-update\ng-alain-master\node_modules\._license-webpack-plugin@1.1.1@license-webpack-plugin\dist\LicenseWebpackPlugin.js:89:27
    at Array.forEach (native)
    at Compiler.<anonymous> (D:\Project\ng-alain-update\ng-alain-master\node_modules\._license-webpack-plugin@1.1.1@license-webpack-plugin\dist\LicenseWebpackPlugin.js:65:32)
    at next (D:\Project\ng-alain-update\ng-alain-master\node_modules\._tapable@0.2.8@tapable\lib\Tapable.js:204:14)
    at D:\Project\ng-alain-update\ng-alain-master\node_modules\._html-webpack-plugin@2.30.1@html-webpack-plugin\index.js:204:9
    at PassThroughHandlerContext.finallyHandler (D:\Project\ng-alain-update\ng-alain-master\node_modules\._bluebird@3.5.1@bluebird\js\release\finally.js:56:23)
</code></pre>
![ng-alain](https://user-images.githubusercontent.com/15085021/36098206-02bf2892-1039-11e8-992f-77d65de20de2.png)

按报错说明，文件夹内容如下：
![ng-alain node_module](https://user-images.githubusercontent.com/15085021/36129176-cdea4b5c-10a0-11e8-9f23-e194823f1378.png)

![ng-alain package](https://user-images.githubusercontent.com/15085021/36129691-64b93a78-10a3-11e8-90ad-654255c8f4a8.png)

node_module中license-webpack-plugin文件夹
![ng-alain license](https://user-images.githubusercontent.com/15085021/36129863-4c6e0e2a-10a4-11e8-8b68-74780096260b.png)

 license-package-plugin中licenseExtractor.js的122-126行代码：

```js
    LicenseExtractor.prototype.readPackageJson = function (packageName) {
        var pathName = path.join(this.modulePrefix, packageName, 'package.json');
        var file = fs.readFileSync(pathName, 'utf8');
        return JSON.parse(file);
    };
```
## Environment

<pre><code>
ng-alain version: 0.6.6
Angular version: 5.2.4
</code></pre>

**Comment by OffieCao** [comment]
使用ng build --prod --extract-licenses=false --vendor-chunk=true 已解决

**Comment by sunger** [comment]
使用ng build --prod --extract-licenses=false --vendor-chunk=true 任然有错误：


D:\go\wks\alain3\ng-alain-0.6.6>
D:\go\wks\alain3\ng-alain-0.6.6>ng build --prod --extract-licenses=false --vendor-chunk=true
Date: 2018-02-19T07:05:52.493Z
Hash: 80a93cac0e6ad0c39802
Time: 9546ms
chunk {scripts} scripts.e50c400a0fae7f0fbf51.bundle.js (scripts) 872 kB [initial] [rendered]
chunk {0} styles.81c946d71ce37a131776.bundle.css (styles) 422 kB [initial] [rendered]
chunk {1} polyfills.997d8cc03812de50ae67.bundle.js (polyfills) 84 bytes [initial] [rendered]
chunk {2} main.ee32620ecd1edff94184.bundle.js (main) 84 bytes [initial] [rendered]
chunk {3} inline.318b50c57b4eba3d437b.bundle.js (inline) 796 bytes [entry] [rendered]

ERROR in ..\ngx-ueditor\index.ts(11,2): Error during template compile of 'UEditorModule'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule'
    'NgModule' calls 'ɵmakeDecorator'.

**Comment by cipchk** [comment]
我尝试一个完全的过程，并无出现你的问题。
