### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by sunny2zhang** [ng-alain/ng-alain#327]
peterzhangdeMacBook-Pro:angularAdmin leleba$ node -v
v9.2.1
peterzhangdeMacBook-Pro:angularAdmin leleba$ npm -v
5.7.1
when I use npm install there are the error: 

events.js:136░░░░░░⸩ ⠇ extract:ng-zorro-antd: sill extract @angular/platform-br
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:237:12)
    at PassThrough.Writable.write (_stream_writable.js:288:5)
    at PassThrough.Writable.end (_stream_writable.js:554:10)
    at ReadEntry.entry.on (/usr/local/Cellar/nvm/0.33.6/versions/node/v9.2.1/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at ReadEntry.emit (events.js:164:20)
    at ReadEntry.emit (/usr/local/Cellar/nvm/0.33.6/versions/node/v9.2.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at ReadEntry.[maybeEmitEnd] (/usr/local/Cellar/nvm/0.33.6/versions/node/v9.2.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:240:12)
    at ReadEntry.end (/usr/local/Cellar/nvm/0.33.6/versions/node/v9.2.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:153:27)
    at Unpack.[consumeBody] (/usr/local/Cellar/nvm/0.33.6/versions/node/v9.2.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/usr/local/Cellar/nvm/0.33.6/versions/node/v9.2.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/usr/local/Cellar/nvm/0.33.6/versions/node/v9.2.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/usr/local/Cellar/nvm/0.33.6/versions/node/v9.2.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at Unzip.emit (events.js:159:13)
    at Unzip.emit (/usr/local/Cellar/nvm/0.33.6/versions/node/v9.2.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at Unzip.write (/usr/local/Cellar/nvm/0.33.6/versions/node/v9.2.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:90:17)
    at Unzip.write (/usr/local/Cellar/nvm/0.33.6/versions/node/v9.2.1/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
events.js:136░░░░░░⸩ ⠏ extract:typescript: sill extract @angular/platform-brows
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:237:12)
    at PassThrough.Writable.write (_stream_writable.js:288:5)
    at PassThrough.Writable.end (_stream_writable.js:554:10)
    at ReadEntry.entry.on (/usr/local/Cellar/nvm/0.33.6/versions/node/v9.2.1/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at ReadEntry.emit (events.js:164:20)
    at ReadEntry.emit (/usr/local/Cellar/nvm/0.33.6/versions/node/v9.2.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at ReadEntry.[maybeEmitEnd] (/usr/local/Cellar/nvm/0.33.6/versions/node/v9.2.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:240:12)
    at ReadEntry.end (/usr/local/Cellar/nvm/0.33.6/versions/node/v9.2.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:153:27)
    at Unpack.[consumeBody] (/usr/local/Cellar/nvm/0.33.6/versions/node/v9.2.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/usr/local/Cellar/nvm/0.33.6/versions/node/v9.2.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/usr/local/Cellar/nvm/0.33.6/versions/node/v9.2.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/usr/local/Cellar/nvm/0.33.6/versions/node/v9.2.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at Unzip.emit (events.js:159:13)
    at Unzip.emit (/usr/local/Cellar/nvm/0.33.6/versions/node/v9.2.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at Unzip.write (/usr/local/Cellar/nvm/0.33.6/versions/node/v9.2.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:90:17)
    at Unzip.write (/usr/local/Cellar/nvm/0.33.6/versions/node/v9.2.1/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
npm WARN ng-alain@0.7.1 No repository field.

npm ERR! cancel after 1 retries!
WARN tar ENOENT: no such file or directory, open '/Users/leleba/workspace/angularAdmin/node_modules/.staging/ace-builds-e66f2408/demo/bookmarklet/images/logo_half.png'
WARN tar ENOENT: no such file or directory, open '/Users/leleba/workspace/angularAdmin/node_modules/.staging/postcss-selector-parser-12549ab5/API.md'

thank you

**Comment by cipchk** [comment]
https://github.com/npm/npm/issues/19989
