### ISSUE TITLE
Can not integrate with angular2-schema-form

### ISSUE THREAD

**Issue by vellengs** [ng-alain/ng-alain#36]
```
ERROR in Error: Error encountered resolving symbol values statically. Calling function 'SchemaFormModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in /Users/xxxxx/projects/ng-alain/src/app/app.module.ts, resolving symbol AppModule in /Users/xxxxx/projects/ng-alain/src/app/app.module.ts
    at syntaxError (/Users/xxxxx/projects/ng-alain/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at simplifyInContext (/Users/xxxxx/projects/ng-alain/node_modules/@angular/compiler/bundles/compiler.umd.js:24979:23)
    at StaticReflector.simplify (/Users/xxxxx/projects/ng-alain/node_modules/@angular/compiler/bundles/compiler.umd.js:24991:13)
    at StaticReflector.annotations (/Users/xxxxx/projects/ng-alain/node_modules/@angular/compiler/bundles/compiler.umd.js:24418:41)
    at _getNgModuleMetadata (/Users/xxxxx/projects/ng-alain/node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (/Users/xxxxx/projects/ng-alain/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (/Users/xxxxx/projects/ng-alain/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/Users/xxxxx/projects/ng-alain/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/Users/xxxxx/projects/ng-alain/node_modules/@ngtools/webpack/src/plugin.js:212:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (/Users/xxxxx/projects/ng-alain/node_modules/@ngtools/webpack/src/plugin.js:448:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

webpack: Failed to compile.

```

**Comment by vellengs** [comment]
I was only added the module and register the module,  then can not build the project.
```
https://github.com/vellengs/ng-alain/tree/master
```
you can see the code changes.

**Comment by cipchk** [comment]
try removing `.forRoot()` part code.

maybe `angular2-schema-form` the `.forRoot()` methods is to complicated for the static reflector to resolve at runtime. 

you can get more information from [#11262](https://github.com/angular/angular/issues/11262).

**Comment by vellengs** [comment]
After removed .forRoot(). 
It's works.
But the issue seems complicated.

**Comment by cipchk** [comment]
this is `angular2-schema-form` problem that even it is empty angular-cli project, my hands are tied!
