### ISSUE TITLE
@delon/cli创建页面报错

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#427]
ng g page create -t=edit --modal=true
````
Your global Angular CLI version (6.0.1) is greater than your local
version (1.7.3). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
Cannot find module 'rxjs-compat/add/operator/merge'
Error: Cannot find module 'rxjs-compat/add/operator/merge'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/xing/Documents/wwwroot/web/node_modules/@delon/cli/node_modules/rxjs/add/operator/merge.js:3:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
````

**Comment by NitronPlus** [comment]
暂时不支持 angular@v6

**Comment by xingkoo** [comment]
我降回来了，还是这个错误。
````
g g page create -t=edit --modal=true
Cannot find module 'rxjs-compat/add/operator/merge'
Error: Cannot find module 'rxjs-compat/add/operator/merge'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/xing/Documents/wwwroot/web/node_modules/@delon/cli/node_modules/rxjs/add/operator/merge.js:3:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
````

````
ng -v

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.7.4
Node: 8.9.3
OS: darwin x64
Angular: 5.2.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.2.5
@angular/cli: 1.7.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.6.2
webpack-bundle-analyzer: 2.11.2
webpack: 3.11.0
````

**Comment by NitronPlus** [comment]
你的Rxjs是v6的吧
