### ISSUE TITLE
Command 'ng g ng-alain:module sys'  report an error

### ISSUE THREAD

**Issue by luokyme** [ng-alain/ng-alain#470]
命令结果如下：
```
Schematic "module" not found in collection "ng-alain".
Error: Schematic "module" not found in collection "ng-alain".
    at SchematicEngine.createSchematic (C:\Users\Xavier\Desktop\ng-alain\seek\node_modules\@angular-devkit\schematics\src\engine\engine.js:155:23)
    at CollectionImpl.createSchematic (C:\Users\Xavier\Desktop\ng-alain\seek\node_modules\@angular-devkit\schematics\src\engine\collection.js:12:29)
    at Object.getSchematic (C:\Users\Xavier\Desktop\ng-alain\seek\node_modules\@angular\cli\utilities\schematics.js:36:23)
    at GenerateCommand.getOptions (C:\Users\Xavier\Desktop\ng-alain\seek\node_modules\@angular\cli\models\schematic-command.js:194:40)
    at GenerateCommand.<anonymous> (C:\Users\Xavier\Desktop\ng-alain\seek\node_modules\@angular\cli\commands\generate.js:38:53)
    at Generator.next (<anonymous>)
    at C:\Users\Xavier\Desktop\ng-alain\seek\node_modules\@angular\cli\commands\generate.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Xavier\Desktop\ng-alain\seek\node_modules\@angular\cli\commands\generate.js:3:12)
    at GenerateCommand.initialize (C:\Users\Xavier\Desktop\ng-alain\seek\node_modules\@angular\cli\commands\generate.js:30:16)
```

按主文档的新增页面小节里指引进行操作的， 我看到了 命令行工具 文档里，标记了Module 命令是待发布，那现在有什么替代命令吗？

**Comment by cipchk** [comment]
https://ng-alain.com/cli/generate#Module-%E6%A8%A1%E5%9D%97%EF%BC%88%E5%BE%85%E5%8F%91%E5%B8%83%EF%BC%89

> 注意标题。

**Comment by Hexor** [comment]
但是并没有在https://ng-alain.com/docs/new-page 中注明当前还不能使用

**Comment by cipchk** [comment]
已发布
