### ISSUE TITLE
npm install 告警问题

### ISSUE THREAD

**Issue by gloriawish** [ng-alain/ng-alain#663]
npm install 后产生下列的告警信息，请问如何消除，谢谢了
npm WARN less-loader@4.1.0 requires a peer of less@^2.3.1 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng-alain@1.4.0 requires a peer of @angular-devkit/core@^0.6.1 but none is installed. You must install peer dependencies yourself.
npm WARN ng-alain@1.4.0 requires a peer of @angular-devkit/schematics@^0.6.1 but none is installed. You must install peer dependencies yourself.
npm WARN ng-alain@1.4.0 requires a peer of @schematics/angular@^0.6.1 but none is installed. You must install peer dependencies yourself.
npm WARN tsickle@0.30.0 requires a peer of typescript@>=2.4.2 <2.9 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.11 (node_modules\canvas):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.11 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

**Comment by cipchk** [comment]
绝大部分依赖警告的提醒目标类库依赖过旧的版本引起的，可以无视它们，另外如果你觉得不可靠，可以采用 [package-lock.json](https://github.com/cipchk/ng-alain/blob/master/package-lock.json) 版本。

**Comment by gloriawish** [comment]
@cipchk 
取消less升级后，npm install 报错如下
ERROR in Module build failed: Error: Cannot find module 'less'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\code\webomt\code\webui\node_modules\less-loader\dist\index.js:7:13)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\code\webomt\code\webui\node_modules\less-loader\dist\cjs.js:3:18)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
ERROR in ./src/styles.less
Module build failed: ModuleBuildError: Module build failed: Error: Cannot find module 'less'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\code\webomt\code\webui\node_modules\less-loader\dist\index.js:7:13)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\code\webomt\code\webui\node_modules\less-loader\dist\cjs.js:3:18)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at runLoaders (E:\code\webomt\code\webui\node_modules\webpack\lib\NormalModule.js:252:20)
    at E:\code\webomt\code\webui\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at E:\code\webomt\code\webui\node_modules\loader-runner\lib\LoaderRunner.js:170:18
    at loadLoader (E:\code\webomt\code\webui\node_modules\loader-runner\lib\loadLoader.js:27:11)
    at iteratePitchingLoaders (E:\code\webomt\code\webui\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (E:\code\webomt\code\webui\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at E:\code\webomt\code\webui\node_modules\loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (E:\code\webomt\code\webui\node_modules\loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (E:\code\webomt\code\webui\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (E:\code\webomt\code\webui\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at E:\code\webomt\code\webui\node_modules\loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (E:\code\webomt\code\webui\node_modules\loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (E:\code\webomt\code\webui\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (E:\code\webomt\code\webui\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
    at NormalModule.doBuild (E:\code\webomt\code\webui\node_modules\webpack\lib\NormalModule.js:235:3)
    at NormalModule.build (E:\code\webomt\code\webui\node_modules\webpack\lib\NormalModule.js:365:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webomt@0.0.1 build: `ng build --prod --build-optimizer`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webomt@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\z00417065\AppData\Roaming\npm-cache\_logs\2018-09-04T03_00_54_809Z-debug.log

**Comment by cipchk** [comment]
尝试移除 `node_modules`、`package-lock.json` 后我重新安装。
