### ISSUE TITLE
ng g ng-alain:plugin icon 执行后出错

### ISSUE THREAD

**Issue by laohoo** [ng-alain/ng-alain#854]
7.0 rc2版本
执行 ng g ng-alain:plugin icon 后编译报错，检查发现是 style-icons-auto.ts 文件更新出现错误，多了个 ' 符号。

**Comment by cipchk** [comment]
@laohoo 能否提供更多细节，我测试并未发现上述错误。

**Comment by xcorpio** [comment]
```
ng g ng-alain:plugin icon
Cannot find module '../core/lang.config'
Error: Cannot find module '../core/lang.config'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
    at Function.Module._load (internal/modules/cjs/loader.js:539:25)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/zhengshaodong/Workspace/github/open-indigo/node_modules/ng-alain/plugin/plugin.default-language.js:4:23)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/zhengshaodong/Workspace/github/open-indigo/node_modules/ng-alain/plugin/index.js:8:35)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
```
之前运行还可以，今天运行报这个

**Comment by cipchk** [comment]
@xcorpio 尝试使用最新版本试试
